-- Clear existing players and re-seed with current top pros (May 2026 rankings)
truncate table rosters cascade;
truncate table draft_picks cascade;
delete from players;

-- Top 50 MPO (Men's) - PDGA World Rankings May 2026
insert into players (name, division, pdga_number) values
  ('Gannon Buhr', 'MPO', '75412'),
  ('Ricky Wysocki', 'MPO', '38008'),
  ('Niklas Anttila', 'MPO', '91249'),
  ('Calvin Heimburg', 'MPO', '45971'),
  ('Isaac Robinson', 'MPO', '50670'),
  ('Paul McBeth', 'MPO', '27523'),
  ('Anthony Barela', 'MPO', '44382'),
  ('Cole Redalen', 'MPO', '79748'),
  ('Adam Hammes', 'MPO', '57365'),
  ('Kyle Klein', 'MPO', '85132'),
  ('Aaron Gossage', 'MPO', NULL),
  ('Ezra Robinson', 'MPO', NULL),
  ('Evan Smith', 'MPO', NULL),
  ('Sullivan Tipton', 'MPO', NULL),
  ('Mauri Villmann', 'MPO', NULL),
  ('Luke Taylor', 'MPO', NULL),
  ('Andrew Marwede', 'MPO', NULL),
  ('Ezra Aderhold', 'MPO', NULL),
  ('Chris Dickerson', 'MPO', NULL),
  ('Simon Lizotte', 'MPO', NULL),
  ('Joseph Anderson', 'MPO', NULL),
  ('Casey White', 'MPO', NULL),
  ('Raven Newsom', 'MPO', NULL),
  ('Paul Krans', 'MPO', NULL),
  ('Corey Ellis', 'MPO', NULL),
  ('Evan Scott', 'MPO', NULL),
  ('Lauri Lehtinen', 'MPO', NULL),
  ('Austin Turner', 'MPO', NULL),
  ('Gavin Babcock', 'MPO', NULL),
  ('Silas Schultz', 'MPO', NULL),
  ('Eagle McMahon', 'MPO', NULL),
  ('Zachary Nash', 'MPO', NULL),
  ('Bradley Williams', 'MPO', NULL),
  ('Joel Freeman', 'MPO', NULL),
  ('Jake Monn', 'MPO', NULL),
  ('Matthew Orum', 'MPO', NULL),
  ('Emerson Keith', 'MPO', NULL),
  ('Jesse Nieminen', 'MPO', NULL),
  ('Parker Welck', 'MPO', NULL),
  ('Andrew Presnell', 'MPO', NULL),
  ('Chandler Kramer', 'MPO', NULL),
  ('Mason Ford', 'MPO', NULL),
  ('Benjamin Callaway', 'MPO', NULL),
  ('Jaden Rye', 'MPO', NULL),
  ('Daniel Davidsson', 'MPO', NULL),
  ('Jakub Semerád', 'MPO', NULL),
  ('Harry Chace', 'MPO', NULL),
  ('Paul Ulibarri', 'MPO', NULL),
  ('Nathan Queen', 'MPO', NULL),
  ('Jake Hebenheimer', 'MPO', NULL),

-- Top 25 FPO (Women's) - PDGA World Rankings May 2026
  ('Holyn Handley', 'FPO', '133547'),
  ('Missy Gannon', 'FPO', '85942'),
  ('Ohn Scoggins', 'FPO', '48976'),
  ('Silva Saarinen', 'FPO', '107335'),
  ('Kristin Lätt', 'FPO', NULL),
  ('Eveliina Salonen', 'FPO', NULL),
  ('Henna Blomroos', 'FPO', NULL),
  ('Paige Pierce', 'FPO', NULL),
  ('Valerie Mandujano', 'FPO', NULL),
  ('Cadence Burge', 'FPO', NULL),
  ('Ella Hansen', 'FPO', NULL),
  ('Jessica Gurthie', 'FPO', NULL),
  ('Kat Mertsch', 'FPO', NULL),
  ('Lisa Fajkus', 'FPO', NULL),
  ('Sofia Donnecke', 'FPO', NULL),
  ('Catrina Allen', 'FPO', NULL),
  ('Hanna Huynh', 'FPO', NULL),
  ('Rebecca Cox', 'FPO', NULL),
  ('Anneli Tõugjas-Männiste', 'FPO', NULL),
  ('Anniken Kristiansen Steen', 'FPO', NULL),
  ('Alexis Mandujano', 'FPO', NULL),
  ('Hailey King', 'FPO', NULL),
  ('Jennifer Allen', 'FPO', NULL),
  ('Taylor Chocek', 'FPO', NULL),
  ('Rebecca Don', 'FPO', NULL);
